---
version: '3.8'
services:
  setup:
    image: node:12
    working_dir: /usr/src/app
    volumes:
      - "${PWD}:/usr/src/app"
  lint:
    image: node:12
    working_dir: /usr/src/app
    volumes:
      - "${PWD}:/usr/src/app"
  spelling:
    image: node:12
    working_dir: /usr/src/app
    volumes:
      - "${PWD}:/usr/src/app"
  links:
    image: node:12
    working_dir: /usr/src/app
    volumes:
      - "${PWD}:/usr/src/app"
